import { Suspense } from 'react';

import { Inter } from 'next/font/google';

import { NavigationEvents } from '@/components/navigation-events';

import './globals.css';
import 'antd/dist/reset.css';

const inter = Inter({ subsets: ['latin'] });

export const metadata = {
	title: 'greedy',
	description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
	return (
		<html lang="zh-CN">
			<body className={inter.className}>
				{children}

				<Suspense fallback={null}>
					<NavigationEvents />
				</Suspense>
			</body>
		</html>
	);
}
